return {
	["enable_VHSs"] = true,
	["enable_Jokers"] = true,
	["enable_Decks"] = true,
	["enable_Partners"] = false,
	["enable_Music"] = true,
	["enable_EasterEggs"] = true,
	["enable_Boosters"] = true,
	["forceDisableOrtalab"] = false,
	["enable_VinnyContent"] = true,
	["enable_Challenges"] = true,
	["forceEnableOrtalab"] = false,
	["enable_SoundPacks"] = true,
	["enable_Logo"] = true,
	["enable_JoelContent"] = true,
	["enable_Sleeves"] = false,
	["enable_Tags"] = true,
	["enable_Stands"] = true,
	["enable_Vouchers"] = true,
	["muteWega"] = false,
	["enable_Blinds"] = true,
	["enable_Consumables"] = true,
	["enable_Editions"] = true,
}