[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/crash_handler.lua"]'
pattern = "table.insert(err, sanitizedmsg)"
position = "before"
payload = "sendDebugMessage(tprint(sanitizedmsg))"
match_indent = true