[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

[[patches]]
[patches.pattern]
target = '''=[SMODS extracredit "src/essay.lua"]'''
pattern = "local mod = SMODS.current_mod"
position = "before"
payload = "-- Test"
match_indent = true