[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# why does this not fucking work man. i just wanna overwrite the crash message so i can tell people to update smods
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/crash_handler.lua"]'''
pattern = "table.insert(err, sanitizedmsg)"
position = "before"
match_indent = true
payload = "sendDebugMessage(tprint(sanitizedmsg))"
times = 1